### ISSUE TITLE
App does not Close (still in background) after 3D tourch or widget enable/disable

### ISSUE THREAD

**Issue by samluxh** [anthonya1999/GoodNight#69] opened 2016-01-05 17:41 UTC
Is that a bug or feature :D

I alway have to close it myelf..

**Comment by wasp604** [comment] 2016-01-05 23:24
There is a feature that closes the app after a 3D touch setting has been
used.

**Comment by mariokorte** [comment] 2016-01-06 12:46
So you say when you use 3Dtouch to activate a setting the app opens and it does not close anymore?

**Comment by samluxh** [comment] 2016-01-06 13:57
If I use 3Dtouch to enable GoodNight, it opens up the app, enables the setting and pushes the app into the background. So i always have to close the app in the taskmanager. So the 3Dtouch feature gets useless, because I can open up the app, enable the setting myself and close the app (in taskmanager).

With 3dtouch it should just enable the setting (maybe without showing up the app?) without the running app in taskmanager, that is 3dtouch made for afaik :)

The same with enable GoodNight with widget, it opens up the app etc...

**Comment by mariokorte** [comment] 2016-01-06 14:04
Well, 
1.) This is how the 3D-Touch is implemented at the moment. I will look into that when I have an iPhone 6s next week. I will surely be able to implement it so that the app doesn't need to be opened. Please be patient.
2.) The newest version with widget (you should use the latest commit from master) does not open the app anymore when using the widget.
3.) You should let the app reside in the task switcher if you use the automatic modes as only then it can work as intended.

**Comment by samluxh** [comment] 2016-01-07 12:05
Allright, thank you, I look forward to it :)

I don´t use the automatic modes at all, so i just close the app :)

**Comment by mariokorte** [comment] 2016-01-18 12:43
OK, so this is not possible without opening the app - this is how it's implemented in iOS. I'm sorry.
In settings you can select whether you want the app to stay open after executing the action or whether it should close itself after it (Exit after Action).

**Closed by mariokorte** 2016-01-18 12:43 UTC
Labels: enhancement
