### ISSUE TITLE
Can't modify "color changing" time if automatic mode is disabled

### ISSUE THREAD

**Issue by RSully** [anthonya1999/GoodNight#19] opened 2015-11-30 21:33 UTC
Tapping the rows "turn on color changing at" and "turn off color changing at" do not do anything.

ping @mariokorte

**Comment by RSully** [comment] 2015-11-30 21:34
Apparently they only work when "automatic color changing (time)" is enabled.

**Comment by mariokorte** [comment] 2015-11-30 21:36
Correct, that works as intended.

**Comment by RSully** [comment] 2015-11-30 21:36
I would like to be able to edit the times regardless of if they're enabled.

There is some other inconsistency though. By default "low temperature night mode" is enabled, even if I had auto color changing disabled. I guess backwards compatibility isn't exactly high priority on a non-app store app.

**Comment by mariokorte** [comment] 2015-11-30 21:49
I should make that visible more clearly by disabling selection of those cells and changing the colour of the text to a grey tone.

**Comment by mariokorte** [comment] 2015-11-30 21:50
Yes to the night mode bug. That will be fixed.

**Comment by mariokorte** [comment] 2015-12-03 15:21
Can also be closed.

**Closed** 2015-12-03 15:25 UTC
